### ISSUE TITLE
Setup Repo Issues

### ISSUE THREAD

**Issue by CodeMeKathy** [CodeMeKathy/glowing-memory#1]

**Comment by CodeMeKathy** [comment]
- Source Repo: https://github.com/the-collab-lab/smart-shopping-list/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc
- Possible Tool: https://github.com/marketplace/actions/github-issue-copier
- 🌟Working Solution → Kamino ([This extension shows a button on Github issue pages that can be used to clon](https://chrome.google.com/webstore/detail/kamino/ffdebockfdjileaojbbccofhgncmioaf?hl=en-US)): 
	- 	ReadMe: https://github.com/gatewayapps/kamino
	- Chrome Extension: https://chrome.google.com/webstore/detail/kamino/ffdebockfdjileaojbbccofhgncmioaf/related?hl=en-US

## Acceptance criteria
- [x] @YolandaHaynes: Copy Issues 1- 6
	- [x] @YolandaHaynes  -> Assign Issue 1 to @CodeMeKathy
	- [x] @YolandaHaynes  -> Assign Issue 2 to @YolandaHaynes 
	- [x] @YolandaHaynes  -> Assign Issue 3 to @YolandaHaynes  && @CodeMeKathy 
- [x] @CodeMeKathy:  Copy Issues 7- 13

**Comment by CodeMeKathy** [comment]
Hi @YolandaHaynes! I found a working tool that allows for the cloning of issues from one repo to separate different repo.  I updated the issue details to reflect the new working solution, Kamino ([This extension shows a button on Github issue pages that can be used to clon](https://chrome.google.com/webstore/detail/kamino/ffdebockfdjileaojbbccofhgncmioaf?hl=en-US)), with links to the directions and resource materials.  See an image of the working button available once viewing a specific issue and one with the settings I opted to set.  If you have any questions, please let me know.

<details>
<summary>Kamino Resource Images</summary>

![image](https://user-images.githubusercontent.com/32943879/214473090-17087b32-1517-4b0e-a3df-c10b00eb964a.png)

![image](https://user-images.githubusercontent.com/32943879/214473542-3fa96640-15c4-452d-84c9-0e3fda677e39.png)

</details>

**Comment by YolandaHaynes** [comment]
@CodeMeKathy Awesome! I'll take a look at it. Thanks for sharing the info!

**Comment by tychiadet** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
bingryan, @newt0, @the-real-astro, @MetaWolves, @tammyyang, @Stefan4D, @Jshanks21, @howeguo, @bruno-fialho, @SubhranilRaha, @0xBosz, @roudra323, @plastikminds, @greglgomez, @0xanonff, @mi2valley, @Bidouyeur, @naveennoel, @SolomonFoskaay, @GandalfsDad, @shunkakinoki, @yaye729125, @Yukaii, @duong-fear, @Alucccard, @Fadi-Haddad, @oXtxNt9U, @6xshushu, @skyve2012, @FunnyArtDesigne, @peng-huang-ch, @waite1x, @GDdark, @ymeng979, @4FutureMediaId, @accavdar, @kynvag, @Hohieu555, @giodemedrano, @axatbhardwaj, @kovoor, @gaslimitreached, @CLT5721, @Seantheprogrammer93, @danielscofield12, @by3wolves, @amandafanny, @ohhkaneda, @DENNIS-CODES, @smckisson
